### ISSUE TITLE
我想要您这个训练别的模型，需要怎样准备数据集呢？

### ISSUE THREAD

**Issue by dogbaha** [ZiweiWangTHU/BiDet#29]
安装voc的格式准备的数据集跑报错了，我不知道是什么原因，如果您方便的话麻烦您帮助我一下

PS D:\project\vscode\BiDet> python .\ssd\train_bidet_ssd.py --data_root='D:\project\vscode\BiDet\data\ea89447d' --basenet='D:\project\vscode\BiDet\ssd\pretrain\vgg16.pth'
Loading base network...
Loading the dataset...
Training SSD on: VOC0712
Using the specified args:
Namespace(basenet='D:\\project\\vscode\\BiDet\\ssd\\pretrain\\vgg16.pth', batch_size=32, clip_grad=False, cuda=True, data_root='D:\\project\\vscode\\BiDet\\data\\ea89447d', dataset='VOC', gamma=0.1, lr=0.001, momentum=0.9, nms_conf_threshold=0.03, num_workers=16, opt='Adam', prior_weight=0.0, reg_weight=0.0, resume=False, sigma=0.0, start_iter=0, weight_decay=0.0, weight_path=None)
C:\Users\dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\dataloader.py:474: UserWarning: This DataLoader will 
create 16 worker processes in total. Our suggested max number of worker in current system is 6 (`cpuset` is not taken into account), which is smaller than what this DataLoader is going to create. Please be 
aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Traceback (most recent call last):
  File ".\ssd\train_bidet_ssd.py", line 418, in <module>
    train()
  File ".\ssd\train_bidet_ssd.py", line 207, in train
    images, targets = next(batch_iterator)
  File "C:\Users\dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\dataloader.py", line 517, in __next__
    data = self._next_data()
  File "C:\Users\dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\dataloader.py", line 1199, in _next_data    
    return self._process_data(data)
  File "C:\Users\dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\dataloader.py", line 1225, in _process_data 
    data.reraise()
  File "C:\Users\dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\_utils.py", line 429, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\_utils\worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>    
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\project\vscode\BiDet\ssd\data\voc0712.py", line 116, in __getitem__
    im, gt, h, w = self.pull_item(index)
  File "D:\project\vscode\BiDet\ssd\data\voc0712.py", line 131, in pull_item
    target = self.target_transform(target, width, height)
  File "D:\project\vscode\BiDet\ssd\data\voc0712.py", line 73, in __call__
    label_idx = self.class_to_ind[name]
KeyError: 'warning'

**Comment by Wuziyi616** [comment]
你好，我猜测你的错误在于 `dataloader` 设置 `num_workers` 数过大，你可以尝试修改[这里](https://github.com/ZiweiWangTHU/BiDet/blob/master/ssd/train_bidet_ssd.py#L61) 到 4 试试

**Comment by dogbaha** [comment]
您好，我已经做了部分修改，我的数据集结构如下
![image](https://user-images.githubusercontent.com/43167127/117781375-29f77b00-b273-11eb-84a8-8ffa8cf489b0.png)
main文件夹下内容如下
![image](https://user-images.githubusercontent.com/43167127/117781570-5c08dd00-b273-11eb-9e06-1b16028950cc.png)

然后我运行如下命令：
PS D:\project\vscode\BiDet> python .\ssd\train_bidet_ssd.py --data_root='D:\project\vscode\BiDet\data\VOCdevkit' --basenet='D:\project\vscode\BiDet\ssd\pretrain\vgg16.pth'  --batch_size=2 --num_workers=4        
Loading base network...
Loading the dataset...
Training SSD on: VOC0712
Using the specified args:
Namespace(basenet='D:\\project\\vscode\\BiDet\\ssd\\pretrain\\vgg16.pth', batch_size=2, clip_grad=False, cuda=True, data_root='D:\\project\\vscode\\BiDet\\data\\VOCdevkit', dataset='VOC', gamma=0.1, lr=0.001, momentum=0.9, nms_conf_threshold=0.03, num_workers=4, opt='Adam', prior_weight=0.0, reg_weight=0.0, resume=False, sigma=0.0, start_iter=0, weight_decay=0.0, weight_path=None)
Traceback (most recent call last):
  File ".\ssd\train_bidet_ssd.py", line 419, in <module>
    train()
  File ".\ssd\train_bidet_ssd.py", line 207, in train
    images, targets = next(batch_iterator)
  File "C:\Users\dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\dataloader.py", line 517, in __next__       
    data = self._next_data()
  File "C:\Users\dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\dataloader.py", line 1199, in _next_data    
    return self._process_data(data)
  File "C:\Users\dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\dataloader.py", line 1225, in _process_data 
    data.reraise()
  File "C:\Users\dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\_utils.py", line 429, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\_utils\worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>    
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\project\vscode\BiDet\ssd\data\voc0712.py", line 122, in __getitem__
    im, gt, h, w = self.pull_item(index)
  File "D:\project\vscode\BiDet\ssd\data\voc0712.py", line 137, in pull_item
    target = self.target_transform(target, width, height)
  File "D:\project\vscode\BiDet\ssd\data\voc0712.py", line 77, in __call__
    label_idx = self.class_to_ind[name]
KeyError: 'warning'


对了，我跑通了您说明中的例子 voc2007 的数据集，但是在跑自己的数据集的时候出现了问题，所以，我猜测可能是您的程序时对数据集的格式有一些要求，不知道是不是这样。 占用您的时间我非常抱歉，如果您有空的话，请帮助我一下下。

**Comment by dogbaha** [comment]
感谢，我已经找到我原因了，数据集的不对，而且有脏数据，经过整理已经跑通了，谢谢

**Comment by Wuziyi616** [comment]
迟复为歉，很高兴你成功跑通了，如果以后遇到新的问题也欢迎提issue交流

**Comment by dogbaha** [comment]
大佬太厉害了，我对你的敬仰和崇拜犹如滔滔江水连绵不绝~
基于您的代码我的期末作业应该稳了，再次感谢
