### ISSUE TITLE
instances_valminusminival2014.json not found

### ISSUE THREAD

**Issue by uzair789** [ZiweiWangTHU/BiDet#35]
Hi,
I am trying to train faster rcnn on the coco dataset. I have downloade the coco dataset following the script that you have provided in the repo. WHen I follow the instructions and start training the model, I get the following error :

    `Traceback (most recent call last):
      File "faster_rcnn/trainval_net.py", line 222, in <module>
        imdb, roidb, ratio_list, ratio_index = combined_roidb(args.imdb_name)
      File "/media/Rozhok/BiDet/faster_rcnn/lib/roi_data_layer/roidb.py", line 119, in combined_roidb
        roidbs = [get_roidb(s) for s in imdb_names.split('+')]
      File "/media/Rozhok/BiDet/faster_rcnn/lib/roi_data_layer/roidb.py", line 119, in <listcomp>
        roidbs = [get_roidb(s) for s in imdb_names.split('+')]
      File "/media/Rozhok/BiDet/faster_rcnn/lib/roi_data_layer/roidb.py", line 112, in get_roidb
        imdb = get_imdb(imdb_name)
      File "/media/Rozhok/BiDet/faster_rcnn/lib/datasets/factory.py", line 38, in get_imdb
        return __sets[name]()
      File "/media/Rozhok/BiDet/faster_rcnn/lib/datasets/factory.py", line 31, in <lambda>
        __sets[name] = (lambda split=split, year=year: coco(split, year))
      File "/media/Rozhok/BiDet/faster_rcnn/lib/datasets/coco.py", line 39, in __init__
        self._COCO = COCO(self._get_ann_file())
      File "/home/biometrics/.virtualenvs/retinanet/lib/python3.6/site-packages/pycocotools/coco.py", line 84, in 
    __init__
        with open(annotation_file, 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 
    '/home/biometrics/data/coco/annotations/instances_valminusminival2014.json'

I dont have the instances_valminusminival2014.json in my annotations folder. Where can I get this from?

**Comment by HBUT-CV** [comment]
https://dl.dropboxusercontent.com/s/o43o90bna78omob/instances_minival2014.json.zip?dl=0
